### ISSUE TITLE
Windows Support and Files

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatModels#89]
**Describe the bug**
While working on checking pysatModels against the pysat v3.0.1 RC (#82), I expanded tests to include windows. This resulted in some test failures on windows related to files that are still left open, but as far as I can tell our code doesn't leave anything open. I think the issue could be coming from the underlying netCDF or HDF libraries. 

**To Reproduce**
1. Run unit tests on windows
2. See error

**Expected behavior**
Unit tests to pass on windows

**Desktop (please complete the following information):**
 - OS: Github Actions 
 - Other details about your setup that could be relevant

**Additional context**

**Comment by jklenzing** [comment]
I'm really not sure what's going on here.  Something is left open, but I don't see that any differences between the downloads here and pysatNASA, which is working for windows.

**Comment by rstoneback** [comment]
I wasn't able to find a problem either 🤷 
The problem also only occurred on half the windows tests. I listed which over in that pull.
I've been stumped hence the issue 🐒

**Comment by jklenzing** [comment]
I've split off a new branch for testing from #82.

The error occurs during the `teardown_class method`, which is why it errors on the last test in that class. From the logs it looks like the dineofs file is still open, although the sami2py file could be open as well.  Verified that pysat 3.0.1 is being used.

**Comment by jklenzing** [comment]
The issue is occurring in the load tests.  Ran a branch where I just deleted these, and it's running fine (ie, the tests download files but do not attempt to read them).  I'm not sure what is different in the load routines here and for the xarray ICON instruments, which are running fine on windows, but at least this narrows it down.

**Comment by aburrell** [comment]
@jklenzing did we fix this?

**Comment by jklenzing** [comment]
This should be solved. The `data.close()` statements in #92 should fix it.  We've also fixed this on the pysat side, but running the `close` command repeatedly should be fine.  We could add `# TODO` statements to remove whenever the next pysat is released, but otherwise this should be closed.
